### ISSUE TITLE
Failed to run inverse_kinematics_motion_planning example: ModuleNotFoundError: No module named 'ompl'

### ISSUE THREAD

**Issue by pengzhenghao** [Genesis-Embodied-AI/Genesis#108]
https://genesis-world.readthedocs.io/en/latest/user_guide/getting_started/inverse_kinematics_motion_planning.html

Traceback (most recent call last):
  File "/home/zhenghao/anaconda3/envs/go/envs/gene/lib/python3.10/site-packages/genesis/engine/entities/rigid_entity/rigid_entity.py", line 1230, in plan_path
    from ompl import base as ob
ModuleNotFoundError: No module named 'ompl'

**Comment by bdelhaisse** [comment]
@pengzhenghao did you install it? https://genesis-world.readthedocs.io/en/latest/user_guide/overview/installation.html#optional-motion-planning

**Comment by vengov** [comment]
I do not see the installation instructions in the provided link. Could you suggest how to successfully install OMPL with python bindings in a virtual environment (venv)?

**Comment by duburcqa** [comment]
You should install the latest main branch, it will install OMPL automatically. Unless you are on Windows, in which case there is no solution I'm afraid.

**Comment by vengov** [comment]
Noted. Thank you. I just installed from OMPL source and seems to be working within a conda environment.
