### ISSUE TITLE
MESA: error: ZINK: failed to choose pdev glx: failed to create drisw screen Exception in thread Thread-2 (_init_and_start_app): Traceback (most recent call last):

### ISSUE THREAD

**Issue by RRGGZZ** [Genesis-Embodied-AI/Genesis#112]
device :[WSL2]
PyOpenGL==3.1.7

the error is 
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
Exception in thread Thread-2 (_init_and_start_app):
Traceback (most recent call last):

**Comment by RRGGZZ** [comment]
I running the example script :

import genesis as gs
gs.init(backend=gs.cpu)

scene = gs.Scene(show_viewer=True)
plane = scene.add_entity(gs.morphs.Plane())
franka = scene.add_entity(
    gs.morphs.MJCF(file='xml/franka_emika_panda/panda.xml'),
)

scene.build()

for i in range(1000):
    scene.step()

**Comment by RRGGZZ** [comment]
and my WSL2 is Ubuntu 24.04.01

**Comment by cloudhu** [comment]
same error

**Comment by cloudhu** [comment]
fixed in Ubuntu
`sudo add-apt-repository ppa:kisak/kisak-mesa  
sudo apt update  
sudo apt upgrade`
