### ISSUE TITLE
display not detected in docker container

### ISSUE THREAD

**Issue by th-yoon** [Genesis-Embodied-AI/Genesis#119]
[ubuntu 22.04 with nvidia gpu]
I tried to run the toy example with the rendering option `genesis.Scene(show_viewer=True)` but `screeninfo` could not detect my display on docker. 

Solution: 
1. allow all local process to the x server before running a docker container: `xhost +Local:*`
2. add following options when running a docker container: `-e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix`

**Comment by th-yoon** [comment]
Then the following error occurred:
`libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast`

Solution:
there is swrast_dri.so in `/usr/lib/x86_64-linux-gnu/dri/`
so I make a link to the path mentioned above:
`ln -s /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so /usr/lib/dri/swrast_dri.so`
(reference: https://forum.step.esa.int/t/snap9-error-libegl-warning-mesa-loader-failed-to-open-swrast/36702/5)

Then the following error occurred:
```libGL error: MESA-LOADER: failed to open swrast: /home/miniconda3/envs/genesis/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-15.so.1) (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast```

Solution:
there was `libstdc++.so.6` in `/usr/lib/x86_64-linux-gnu/`, so I created a link to the path with
```ln  -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30 /home/miniconda3/envs/genesis/lib/libstdc++.so.6.0.30```

and set `LD_LIBRARY_PATH` in conda with
```export LD_LIBRARY_PATH=/home/miniconda3/envs/genesis/lib:$LD_LIBRARY_PATH```

Then it worked for me.

**Comment by zyz-code** [comment]
thanks
