### ISSUE TITLE
AttributeError: module 'genesis' has no attribute 'generate'

### ISSUE THREAD

**Issue by clairelee5740** [Genesis-Embodied-AI/Genesis#150]
I found this project amazing and hope to try out as in the demo video

here is my code:
```
import genesis as gs

gs.generate("A water droplet drops onto a beer bottle ans then slowly slides down along the bottle surface.")
```

However, it says:
```
Traceback (most recent call last):
  File "...\genesis_test.py", line 2, in <module>
    gs.generate("A water droplet drops onto a beer bottle ans then slowly slides down along the bottle surface.")
AttributeError: module 'genesis' has no attribute 'generate'
```

I have installed genesis-world

Is there anyone facing the same problem and how do you solve it? Thanks!

**Comment by clairelee5740** [comment]
OK I found in #30 that the generate function is not released yet, as in the readme it says 

> Some of the modules integrated existing papers and some are still under submission. Access to our generative feature will be gradually rolled out in the near future

So currently, what can Genesis do now???

**Comment by zhouxian** [comment]
Hi, thank you for your interest! Genesis's upper level generative system is a modular framework consisting of multiple modules, and is not ready for public access yet. As of this stage, we are only releasing the low level physics engine.

**Comment by jzc1994** [comment]
same question！

**Comment by ziyanx02** [comment]
We will continue to provide updates about the generative framework in #6, so stay tuned!
