### ISSUE TITLE
function 'glGetUniformLocation' not found

### ISSUE THREAD

**Issue by chenfei8888** [Genesis-Embodied-AI/Genesis#151]
code:
import genesis as gs
gs.init(backend=gs.cpu)

scene = gs.Scene(show_viewer=True)
plane = scene.add_entity(gs.morphs.Plane())
franka = scene.add_entity(
    gs.morphs.MJCF(file='xml/franka_emika_panda/panda.xml'),
)

scene.build()

for i in range(1000):
    scene.step()

error: function 'glGetUniformLocation' not found

**Comment by chenfei8888** [comment]
4090, CUDA 12.3

**Comment by manuelgardina** [comment]
Same code, 4090 12.1 cuda and cpu print the same error

**Comment by 15921483570** [comment]
haven't sovled yet, refer to #12

**Comment by chenfei8888** [comment]
> haven't sovled yet, refer to #12

thanks!

**Comment by ziyanx02** [comment]
Close as a duplicate.
