### ISSUE TITLE
Config bugs when running `python examples/locomotion/go2_train.py`

### ISSUE THREAD

**Issue by DuinoDu** [Genesis-Embodied-AI/Genesis#154]
Hi, thanks for great job!
I try to execute `python examples/locomotion/go2_train.py` but get much bugs about on_policy_runner config. Is this feature under developing?

**Comment by ziyanx02** [comment]
Could you let us know the version of `rsl_rl` you are using? 

There is a significant difference between 2.0.1 (automatically installed via `pip install rsl_rl`) and 1.0.2

**Comment by SuanCai-Fish** [comment]
> Could you let us know the version of `rsl_rl` you are using?您能否告诉我们您正在使用的`rsl_rl`版本？
> 
> There is a significant difference between 2.0.1 (automatically installed via `pip install rsl_rl`) and 1.0.22.0.1（通过`pip install rsl_rl`自动安装）和 1.0.2 之间存在显着差异



> Hi, thanks for great job!您好，感谢您的出色工作！ I try to execute `python examples/locomotion/go2_train.py` but get much bugs about on_policy_runner config. Is this feature under developing?我尝试执行 `python examples/locomotion/go2_train.py` 但关于 on_policy_runner 配置有很多错误。该功能正在开发中吗？

I'm a beginner for learning RL. I follow the User Guide in "Training Locomotion Policies with RL". Is the only thing I need to do is to "Install rsl_rl"? or there is something i forget to do? I can't seem to find a file named "go2_train.py. Could you let me know which step i forget to do?

**Comment by ziyanx02** [comment]
> > Could you let us know the version of `rsl_rl` you are using?您能否告诉我们您正在使用的`rsl_rl`版本？
> > There is a significant difference between 2.0.1 (automatically installed via `pip install rsl_rl`) and 1.0.22.0.1（通过`pip install rsl_rl`自动安装）和 1.0.2 之间存在显着差异
> 
> > Hi, thanks for great job!您好，感谢您的出色工作！ I try to execute `python examples/locomotion/go2_train.py` but get much bugs about on_policy_runner config. Is this feature under developing?我尝试执行 `python examples/locomotion/go2_train.py` 但关于 on_policy_runner 配置有很多错误。该功能正在开发中吗？
> 
> I'm a beginner for learning RL. I follow the User Guide in "Training Locomotion Policies with RL". Is the only thing I need to do is to "Install rsl_rl"? or there is something i forget to do? I can't seem to find a file named "go2_train.py. Could you let me know which step i forget to do?

Yes, the only thing you need to do is to install rsl_rl (v1.0.2) from here: https://github.com/leggedrobotics/rsl_rl/releases/tag/v1.0.2
Please ensure you are in `examples/locomotion` directory before trying to run `go2_train.py`.

If you encounter any other issues, feel free to open a new one to let us know.

**Comment by ziyanx02** [comment]
Here is another rl example for Genesis installed by `pip install genesis-world`:
https://github.com/ziyanx02/Genesis-backflip

**Comment by Nate711** [comment]
I have the same issue even using v1.0.2
