### ISSUE TITLE
User Guide Scene Build operation fails

### ISSUE THREAD

**Issue by CompendiaUI** [Genesis-Embodied-AI/Genesis#167]
scene build operation in user guide
https://genesis-world.readthedocs.io/en/latest/user_guide/getting_started/hello_genesis.html
fails with this error
AttributeError: function 'glGetUniformLocation' not found

**Comment by ziyanx02** [comment]
If you are using Windows, please refer to #12 for more information.
I will close this issue since no further information has been provided.
