### ISSUE TITLE
self collision

### ISSUE THREAD

**Issue by kelo020304** [Genesis-Embodied-AI/Genesis#192]
![img_v3_02hp_ba1284cf-35c1-405d-afce-9ad7d8154e9g](https://github.com/user-attachments/assets/7dc961f3-920b-497b-a3fa-5621236931a7)
I used Piper arm in genesis, why It can not avoid self collision? How to solve it?

**Comment by zhouxian** [comment]
you can turn it on in rigid_options :)

**Comment by ziyanx02** [comment]
When creating the scene, set `rigid_options=gs.options.RigidOptions(enable_self_collision=True, *other_args)`
