### ISSUE TITLE
This is truly an inspiring project. May I ask how the progress is going and if there is an estimated release date?

### ISSUE THREAD

**Issue by legatoo** [Genesis-Embodied-AI/Genesis#2]
Looking forward to your outstanding work.

**Comment by zhouxian** [comment]
Oct 31st or Nov 9th :)

**Comment by StarCycle** [comment]
@zhouxian Now we are definitely waiting for Nov 9!

**Comment by zhouxian** [comment]
Unfortunately, as much as we want to release it soon, we are still packing up all the demos we have, and there's just too many things we want to show... so it might take some more time
