### ISSUE TITLE
`set_friction_ratio` throw error when one link has multiple geometries

### ISSUE THREAD

**Issue by lupinjia** [Genesis-Embodied-AI/Genesis#208]
I want to call `set_friction_ratio` function to set friction ratios for RigidEntities, but get error below: 
![Screenshot from 2024-12-21 21-28-56](https://github.com/user-attachments/assets/934e394c-f113-43b4-bc6c-4aeb62a2fb59)
I try to debug what happened, and found that if `merge_fixed_links = True` when you add a URDF entity with multiple links merged to one link, the list in the `torch.tensor()` call(which is in the source of `set_friction_ratio()`) will have different length in dim1(just as the second figure below), and that will cause the above error.
![Screenshot from 2024-12-21 21-31-13](https://github.com/user-attachments/assets/dd2263cc-621e-4d23-af94-5eed79eafe91)
![Screenshot from 2024-12-21 21-22-19](https://github.com/user-attachments/assets/b88fd44a-3a6e-4209-88f9-35f609cdd87f)

Strictly speaking, this is not a issue if you set `merge_fixed_links=False` when adding a URDF entity, but it should be noted.

**Comment by ziyanx02** [comment]
Thank you for bringing this up! You can use `set_geoms_friction_ratio` in `RigidSolver` for now before we fix it.
https://github.com/ziyanx02/Genesis-backflip/blob/main/locomotion_env.py#L806
