### ISSUE TITLE
Camera not supported in windows

### ISSUE THREAD

**Issue by dasvin3** [Genesis-Embodied-AI/Genesis#218]
Hi Genesis,

I have installed Genesis world and pytorch and after running differential_push python file in cmd(Win10), getting below error
But if I comment out the camera initialization, it runs without error showing values of substep but does not show any scenes 
 
![Camera_issue](https://github.com/user-attachments/assets/ae107318-1d5d-4159-9aee-f97c8970272f)

Regards
Vipin

**Comment by ziyanx02** [comment]
The viewer is not supported in Windows in the current version of Genesis. Please refer to #12 for more information.
