### ISSUE TITLE
General training support

### ISSUE THREAD

**Issue by yic03685** [Genesis-Embodied-AI/Genesis#245]
Hi, will there be supports for non-robot motion? For example, besides the character motion provided by the framework, will there be training function to support custom motions?

**Comment by zhouxian** [comment]
Could you provide a reference/example explaining what you mean in details?

**Comment by yic03685** [comment]
Sure and apologizing for my lack of context. I’m confused how the character motions in the demo were trained? Were all motions trained by individually IK training and used to train the generative model? Will there be support for training custom motions? I understand the generative component still work in progress but if there’s some light document or diagram explaining the connection or IO between the generative and the physic engines, it’d be very helpful. Thanks

**Comment by ziyanx02** [comment]
Here is the paper that may help you: 
https://frank-zy-dou.github.io/projects/CASE/index.html
