### ISSUE TITLE
solve_cubic is wrong?

### ISSUE THREAD

**Issue by yliu000** [Genesis-Embodied-AI/Genesis#254]
in file genesis/utils/bvh.py

To my understanding, "solve_cubic" should be solving a cubic equation.

But running solve_cubic(1, 0, 0, 1)  (x^3+1),  it returns:
1, -0.000000, 0.000000, 1.000000

This is wrong.

Looking at code:
def solve_cubic(a, b, c, d):
    nr = 0
    x0 = x1 = x2 = 1.0
    ncrit, xc0, xc1 = solve_quadratic(3 * a, 2 * b, c)
    if ncrit == 0:
        x0 = newtons_method(a, b, c, d, xc0, 0)
        nr = 1
    elif ncrit == 1:
        nr, x0, x1 = solve_quadratic(3 * a, 2 * b, c)
    ...
    
    
I don't understand why when "ncrit==1", it returns solve_quadratic(3*a, 2*b, c)

**Comment by YilingQiao** [comment]
Hi, @yliu000 We are not using `bvh.py` in this version. How did you get there?

**Comment by yliu000** [comment]
OK. I was just browsing the code.
I'll close issue then.
