### ISSUE TITLE
gs.generate DOESNT exist

### ISSUE THREAD

**Issue by fire17** [Genesis-Embodied-AI/Genesis#261]
Hi there,
was really impressed with the recent online "Generate" demos...

installed using pip,
**I dont see any .generate() function...**
am i missing something? i did have some dep issues, but not sure that it would cause the func to not appear

thanks a lot & all the best!

<img width="1708" alt="image" src="https://github.com/user-attachments/assets/44ec9c9c-5d2a-4168-80bb-d0140180f03b" />

**Comment by ziyanx02** [comment]
We greatly appreciate your interest in Genesis! Access to the generative framework will be rolled out gradually in the near future. We will continue to provide updates in #6, so stay tuned!
