### ISSUE TITLE
How can I use gs.generate? 

### ISSUE THREAD

**Issue by cumbersomeamir** [Genesis-Embodied-AI/Genesis#286]
It is shown in the demo videos but can't find any function like this for text to simulation generation.

**Comment by pronoobe** [comment]
别看了，骗人的

**Comment by ziyanx02** [comment]
Please refer to #6 for update. Close as a duplicate.

**Comment by pronoobe** [comment]
??7傔?D3衭{*俘俔@***@***.***|!x??о瞂ftwn&?鼑  箱襒眘)喵  d?輑田璐Vm系y1太莭W棆鲾窓眙霿рd??e菄躞 tXF;驌
