### ISSUE TITLE
TypeError: __repr__ returned non-string (type NoneType)

### ISSUE THREAD

**Issue by chadwick-yao** [Genesis-Embodied-AI/Genesis#319]
Following [Interactive Information Access and Debugging](https://genesis-world.readthedocs.io/en/latest/user_guide/getting_started/interactive_debugging.html)

Info about ipdb:
> pip show ipdb
Name: ipdb
Version: 0.13.13

```python
     16 import ipdb
     17 
---> 18 ipdb.set_trace()

ipdb> scene
*** TypeError: __repr__ returned non-string (type NoneType)
```

**Comment by milong26** [comment]
my ipython has similar problem

**Comment by zhouxian** [comment]
Hi this seems to be caused by PR #186 , we are working on it
