### ISSUE TITLE
容器运行会强制要求display，有官方解决方案么？

### ISSUE THREAD

**Issue by Shikairan** [Genesis-Embodied-AI/Genesis#324]
我使用k8s或docker启动dockerfile编译好的容器运行demo会失败，genesis强制要求宿主机有display设备。
运行在这里 from genesis.ext import pyrender, trimesh 会出错；
报错：_tkinter.TclError: couldn't connect to display "host.docker.internal:0.0"

**Comment by Shikairan** [comment]
所以现在genesis是没有任何上集群的计划么？

**Comment by Genesis-Embodied-AI** [comment]
Could you repost in english? and @Kashu7100 can take a look

On many clusters it runs fine

**Comment by zhouxian** [comment]
This seems to be relevant to a problematic PR (https://github.com/Genesis-Embodied-AI/Genesis/pull/92)

If you install via pip, it should work. We are trying to resolve the issue in the github version now
