### ISSUE TITLE
Issues of Precision in Physical Simulation

### ISSUE THREAD

**Issue by formoree** [Genesis-Embodied-AI/Genesis#325]
Hello, author. First of all, I would like to express my sincere gratitude for your creation of such a remarkable work! Recently, I have been conducting research on a multi-task framework for quadrupedal and humanoid robots, and I am preparing to migrate it to the Genesis framework. I would like to inquire whether the physics simulation in Genesis 0.2.0 can support simulation training and deployment for humanoid robots.

Thank you very much for your response.

**Comment by Kashu7100** [comment]
Yes, Genesis is fully capable for humanoid training and deployment.

**Comment by formoree** [comment]
ok Thank you very much
