### ISSUE TITLE
Could anyone upload a docker image for us?  This project asks for tricky env......

### ISSUE THREAD

**Issue by zhrli** [Genesis-Embodied-AI/Genesis#331]
Thanks

**Comment by skurtyyskirts** [comment]
One was added yesterday! Look at the recent news, along with the commands to get it started on the frontpage here.

**Comment by ziyanx02** [comment]
Please check [docker usage](https://github.com/Genesis-Embodied-AI/Genesis#docker) for using Genesis in docker.
