### ISSUE TITLE
物体切割出现异常

### ISSUE THREAD

**Issue by xxyyer** [Genesis-Embodied-AI/Genesis#351]
您好，感谢。
我修改examples中的cloth_on_rigid.py代码为：
    
```
   cutter = scene.add_entity(
        morph=gs.morphs.Mesh(
            file="meshes/cross_cutter.obj",
            euler=(90, 0, 0),
            scale=0.8,
            pos=(0.5, 0.5, 0.2),
            fixed=True,
            convexify=False,
        ),
        surface=gs.surfaces.Iron(),
    )

    cloth = scene.add_entity(
        # material=gs.materials.PBD.Cloth(),
        material=gs.materials.MPM.Elastic(),
        morph=gs.morphs.Mesh(
            file="meshes/cloth.obj",
            scale=1.0,
            pos=(0.5, 0.5, 0.5),
            euler=(180.0, 0.0, 0.0),
        ),

        surface=gs.surfaces.Default(
            color=(0.6, 1.0, 0.8, 1.0),
        ),
    )
```

但是出现问题：
![Uploading 问题截图.jpg…]()

**Comment by zhenjia-xu** [comment]
`cloth.obj` is a single-layer mesh, which is not suitable for MPM simulations. Typically, MPM is good at simulating volumetric objects.
For cutting an MPM object, `cut_dragon.py` serves as a good reference.
However, if your goal is to cut a piece of cloth, I’m sorry to inform you that this is not currently supported. The PBD solver used in the cloth simulator does not support fracture.

**Comment by xxyyer** [comment]
OK，thank you ！
