### ISSUE TITLE
How to keep one robot static while another working?

### ISSUE THREAD

**Issue by milong26** [Genesis-Embodied-AI/Genesis#356]
Alternatively i can let the two robots work together,but i'm afraid of collision.

For example,I got 2 paths for each other
```python
for waypoint in path1:
    franka1.control_dofs_position(waypoint)
    # scene.step()
#

# 执行规划路径
for waypoint in path2:
    franka2.control_dofs_position(waypoint)
    # scene.step()
```
If `scene.step()` used,i can see franka1 move first and franka2 fell down for gravity. Then franka2 moved from ground(this may cause error like this`Error:   RRTConnect: Motion planning start tree could not be initialized!
         at line 219 in /project/src/ompl/geometric/planners/rrt/src/RRTConnect.cpp
` but mine not in these code.)

But when i commented scene.step and add scene.step after the code, the scene would show the two robots moved fast.

How to deal with it? If I can't let one keep static, I can keep them 2 move in same step ..

thanks!

**Comment by zhouxian** [comment]
you can simply do position control `franka.control_dofs_position(static_joint_pos_you_want)`
