### ISSUE TITLE
Fatal Error: unable to install Genesis

### ISSUE THREAD

**Issue by younes-io** [Genesis-Embodied-AI/Genesis#361]
Unfortunately, I have several times for a couple of hours now, by executing the command as mentioned in the README `docker build -t genesis -f docker/Dockerfile docker` and I eventually get this:

![image](https://github.com/user-attachments/assets/26b7d79a-4452-42a3-acf9-2a22a086867a)

I'm on WSL2 Debian, and I have dedicated 16GB of RAM to WSL2

**Comment by younes-io** [comment]
@zhouxian : could you please help with this?

**Comment by zhouxian** [comment]
@Kashu7100

**Comment by younes-io** [comment]
I just realized the issue might be related to the fact I'm running this on Debian and in the dockerfile I can see `RUN add-apt-repository ppa:ubuntu-toolchain-r/test && \`

**Comment by Kashu7100** [comment]
Yeah that can be a problem. Also, if you don't need the rendering capability, you can comment out the Luisa build part, which will simplify the entire pipeline (will be a good sanity check).

**Comment by younes-io** [comment]
thanks @Kashu7100 , I actually need the rendering capability.. I'm installing Ubuntu 24 now, and I'll try this out and see.. I'll close this issue though as it's related to my Debian distro
