### ISSUE TITLE
How to merge links connected via a fixed joint in genesis from different urdfs

### ISSUE THREAD

**Issue by hhuang-xu** [Genesis-Embodied-AI/Genesis#378]
Hello, I would like to fix the links of robots from two separate URDF files in Genesis. However, I prefer not to create a new URDF to connect the two robots. Could you please advise on how to achieve this? Does Genesis offer an interface with such functionality?

**Comment by zhouxian** [comment]
At this point you’ll have to edit the URDF I think. We are indeed working on an interface for editing the robot via GUI but this is not something that will be done in a few weeks…
