### ISSUE TITLE
Is there a demo video of gymnastics generated by Genesis available?

### ISSUE THREAD

**Issue by tumluliu** [Genesis-Embodied-AI/Genesis#38]
in order to understand its different understanding of physics other than the existing AI video generators

e.g.

https://imgur.com/a/heres-sora-generated-video-of-gymnastics-LQyKTf0 

Thanks

**Comment by antragoudaras** [comment]
Nice question, or how do we even generate a video after installation? The demos in Twitter (X) it is demonstrated using gs.generate, but when looking at their documentation I did not find anything similar.

**Comment by zhouxian** [comment]
Hi we are only opensourcing the low-level physics engine so far as written in the twitter. The generative work requires quite a bit of more work before ready for public use, but we are working on it:)

**Comment by tumluliu** [comment]
thanks! Looking forward to seeing a generated gymnastics video with normal physics, either as a demo or (the best, if possible) from my local env with your open codebase
