### ISSUE TITLE
Update `pyproject.toml` to include torch and trimesh dependencies

### ISSUE THREAD

**Issue by TheFloatingString** [Genesis-Embodied-AI/Genesis#389]
Hi! Running on Linux, I ran into missing dependency errors with torch and trimesh.

Would if be helpful if I were to create a new PR with torch and trimesh added in the `pyproject.toml` file? (Either as part of the default installation, or with an optional flag?)

**Comment by zhouxian** [comment]
Torch should be installed separately.
We don't rely on public version of trimesh -- we have an internal version  under `genesis/ext/`
