### ISSUE TITLE
Inverse Kinematics & Motion Planning- tutorial code error

### ISSUE THREAD

**Issue by ruk-shan** [Genesis-Embodied-AI/Genesis#394]
When I run the tutorial code, i get this error. "`qpos_start` exceeds joint limit. Relaxing joint limit to contain `qpos_start` for planning."

**Comment by zhouxian** [comment]
this is not error, it's a warning
it simply means the initial configuration exceeds the joint limit, so the planner will relax the joint limit to contain the initial configuration
