### ISSUE TITLE
AttributeError: module 'LuisaRenderPy' has no attribute 'create_scene'

### ISSUE THREAD

**Issue by saprrow** [Genesis-Embodied-AI/Genesis#44]
![Screenshot from 2024-12-19 17-31-47](https://github.com/user-attachments/assets/d3bf7c5c-9887-450a-add9-9fe575745143)

When running **gs.renderers.RayTracer()**, I get an error saying that module 'LuisaRenderPy' has no attribute 'create_scene'. However, I cannot find the 'create_scene' API in LuisaRenderPy's pybind API code.

**Comment by zhouxian** [comment]
@YilingQiao could this be due to a commit mismatch?

**Comment by YilingQiao** [comment]
I changed the commit number. Can you try again?

**Comment by Xu-Xuanhui** [comment]
@YilingQiao 
I built Alif-01'LuisaRender fork. However,  I cannot find the 'create_scene' API in LuisaRenderPy's pybind API code too. 

 print(dir(LuisaRenderPy))
['Camera', 'Integrator', 'LogLevel', 'Shape', 'Spectrum', 'Surface', 'Texture', 'Transform', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'add_emission', 'add_environment', 'add_surface', 'destroy', 'init', 'render_frame', 'update_camera', 'update_shape']
It seems that LuisaRenderPy don't have 'create_scene' ?

**Comment by Xu-Xuanhui** [comment]
I have install the LuisaRender
Ubuntu 22.04 Nvidia driver 535.183.01,cuda 12.2! I update the cuda! python 3.10
git clone https://github.com/Genesis-Embodied-AI/Genesis.git
cd Genesis
git submodule update --init --recursive

You should follow the user guider to install the Dependencies.

cd genesis/ext/LuisaRender
cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D PYTHON_VERSIONS=3.10 -D LUISA_COMPUTE_DOWNLOAD_NVCOMP=ON -D LUISA_COMPUTE_ENABLE_GUI=OFF 
cmake --build build -j $(nproc)

Finall I copy the etx folder to my conda envs.
It works!

**Comment by zswang666** [comment]
Yet again thanks @Xu-Xuanhui  :D 

doc [here](https://genesis-world.readthedocs.io/en/latest/user_guide/getting_started/visualization.html#photo-realistic-ray-tracing-rendering)
