### ISSUE TITLE
Is it possible to introduce the IKfast solver in OpenRAVE into Genesis?

### ISSUE THREAD

**Issue by WenzheHe** [Genesis-Embodied-AI/Genesis#53]
Genesis is a great work in simulation of robot. As far as I know, the IKfast solver in OpenRAVE is currently one of the best solvers for accurately solving the inverse solution of a robotic arm, so can it be brought into Genesis?

**Comment by zhouxian** [comment]
Yeah IKfast is great.

The issues with ikfast is: it's not general for arms more than 6 dofs (correct me if i understood it incorrectly), and it doesn't support gpu parallelization well. so at this stage it might be a bit tricky. Feel free to propose a solution if you have any idea

**Comment by WenzheHe** [comment]
Thanks for your reply! I'll continue to look forward to future updates of Genesis!
