### ISSUE TITLE
LuisaRender submodule not present?

### ISSUE THREAD

**Issue by nlevnaut** [Genesis-Embodied-AI/Genesis#7]
Hello, first off thank you for sharing this, and great work!

It doesn't look like the LuisaRender submodule is present in the genesis/ext/ dir, as described in the [installation guide](https://genesis-world.readthedocs.io/en/latest/user_guide/overview/installation.html#get-luisarender). Maybe I'm missing something?

**Comment by YilingQiao** [comment]
Thanks! Can you try with the latest main branch?

**Comment by nlevnaut** [comment]
I see both submodules under ext now, thank you.

**Comment by nlevnaut** [comment]
I see both submodules under ext now, thank you.
