### ISSUE TITLE
AttributeError: function 'glGetUniformLocation' not found

### ISSUE THREAD

**Issue by vegetabledogzy** [Genesis-Embodied-AI/Genesis#73]

**Comment by vegetabledogzy** [comment]
Windows sys

**Comment by HUWENBIN2024** [comment]
I also met this problem in windows.

**Comment by Dingrui-Wang** [comment]
![Screenshot from 2024-12-19 16-15-04](https://github.com/user-attachments/assets/67dae350-40a9-4ab7-bccf-3a5b0ee2c443)
They don't support visualization on window lol

**Comment by barius** [comment]
same issue here: https://github.com/Genesis-Embodied-AI/Genesis/issues/12

**Comment by ziyanx02** [comment]
Close as a duplicate.
