### ISSUE TITLE
windows平台下是不是暂时还无法完全体验Genesis的所有特性？

### ISSUE THREAD

**Issue by NatureDoor** [Genesis-Embodied-AI/Genesis#88]
windows平台下是不是暂时还无法完全体验Genesis的所有特性？
我今天通过示例进行测试的时候，发现报错**`AttributeError: function 'glGetUniformLocation' not found`**
![image](https://github.com/user-attachments/assets/90e03b3f-7a3a-47f5-94bd-baae5906c0f7)
建议尽快支持windows平台，谢谢。

**Comment by LangevinFlow** [comment]
建议先搞清glGetUniformLocation和windows和linux的关系再提issue。

**Comment by sunshineinheart** [comment]
这个问题可以通过 https://github.com/Genesis-Embodied-AI/Genesis/issues/12#issuecomment-2557010981 解决。
当然目前体验确实 windows 平台问题蛮多的，我这里目前还渲染不出来。

**Comment by flashal1** [comment]
> 这个问题可以通过 [#12 (comment)](https://github.com/Genesis-Embodied-AI/Genesis/issues/12#issuecomment-2557010981) 解决。 当然目前体验确实 windows 平台问题蛮多的，我这里目前还渲染不出来。

在win上面我已经可以跑通了，但问题是只有黑窗口没有渲染图

**Comment by ziyanx02** [comment]
Close as a duplicate.
