### ISSUE TITLE
BUG at RigidEntity.set_friction_ratio()

### ISSUE THREAD

**Issue by Hellod035** [Genesis-Embodied-AI/Genesis#97]
RigidEntity.set_friction_ratio() has some implementation bugs and does not work properly. Here are the fixes available.

```
    def set_friction_ratio(self, friction_ratio, link_indices, envs_idx=None):
        """
        Set the friction ratio of the geoms of the specified links.
        Parameters
        ----------
        friction_ratio : torch.Tensor, shape (n_envs, n_links)
            The friction ratio
        link_indices : array_like
            The indices of the links to set friction ratio.
        envs_idx : None | array_like, optional
            The indices of the environments. If None, all environments will be considered. Defaults to None.
        """
        geom_indices = [
            self._links[j]._geom_start + i 
            for j in link_indices
            for i in range(self._links[j].n_geoms)
        ]
        
        expanded_ratios = torch.cat(
            [
                ratio.unsqueeze(-1).repeat(1, self._links[j].n_geoms)
                for j, ratio in zip(link_indices, friction_ratio.unbind(-1))
            ],
            dim=-1,
        )
        
        self._solver.set_geoms_friction_ratio(
            expanded_ratios,
            torch.tensor(geom_indices, dtype=torch.int32),
            envs_idx,
        )
```

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

This change fixes the implementation bugs in the set_friction_ratio() method of the RigidEntity class. The main improvements are:
1. Correctly handle the shape of friction_ratio tensor
2. Properly expand the friction ratios for each geom
3. Use the correct dtype for geom indices
4. Simplify the logic for creating geom indices

You can review changes in this commit: https://github.com/wwqwq2313/Genesis-Embodied-AI-Genesis-97/commit/eb908b51db5b0f03e05c101c1d02d5278919e6ed.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
